@file:JvmName("AruExported")
@file:Suppress("unused")

/*
 * file "exported.kt". DO NOT EDIT MANUALLY. THIS FILE IS GENERATED BY GRADLE.
 */

package pw.aru.exported

/**
 * Aru! Version
 */
const val aru_version = "2.0.1"

/**
 * Kotlin Version
 */
const val kotlin_version = "1.2.51"

/**
 * User Agent
 */
const val user_agent = "JDA/DiscordBot (Aru! 2.0.1)"